name: 'Terraform Deployment'

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: 'Dockerization'
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get Latest Image Version
        id: get_version
        run: |
          REPO_NAME="${{ vars.DOCKER_REPO }}/prod-nginx"
          LATEST_VERSION=$(curl -s "https://hub.docker.com/v2/repositories/$REPO_NAME/tags" | jq -r '[.results[].name | select(. | test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))] | sort_by(split(".") | map(tonumber)) | last' || echo "1.0.0")
          
          # Increment the version (e.g., 1.0.0 -> 1.0.1)
          NEW_VERSION=$(echo $LATEST_VERSION | awk -F. '{print $1"."$2"."$3+1}')
          
          echo "Latest Version: $LATEST_VERSION"
          echo "New Version: $NEW_VERSION"
          
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          REPO_NAME="${{ vars.DOCKER_REPO }}/prod-nginx"
          
          docker build --no-cache -t $REPO_NAME:${{ env.NEW_VERSION }} --build-arg ENV_FILE_PATH=src/.env -f docker/prod/LaravelLynxProd.Dockerfile .
          
          docker push $REPO_NAME:${{ env.NEW_VERSION }}

      - name: Logout from Docker Hub
        run: docker logout

  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    needs: build
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./terraform/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Latest NGINX Tag
        id: fetch_nginx_tag
        run: |
          LATEST_TAG=$(curl -s https://hub.docker.com/v2/repositories/${{ vars.DOCKER_REPO }}/prod-nginx/tags \
            | jq -r '[.results[].name | select(. | test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))] | sort_by(split(".") | map(tonumber)) | last')
          
          echo "Latest Tag: $LATEST_TAG"
          echo "nginx_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Initialize Terraform (Local Backend)
        run: |
          terraform init -backend=false  # Use local state
#          cd terraform  # Navigate to Terraform directory in the repo

#      - name: Terraform Plan
#        run: |
#          terraform plan -var "azure_subscription=${{ secrets.AZURE_SUBSCRIPTION }}" \
#            -var "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" \
#            -var "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" \
#            -var "nginx_tag=${{ env.VERSION }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var "azure_subscription=${{ secrets.AZURE_SUBSCRIPTION }}" \
            -var "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" \
            -var "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" \
            -var "nginx_tag=${{ env.VERSION }}"
